config/routes.rb
Rails.application.routes.draw do
  resources :negocios
  get '/', to: 'negocios#index'

end

app/models/negocio.rb
class Negocio < ActiveRecord::Base
def self.search(search)
  # Title is for the above case, the OP incorrectly had 'name'
  where("name LIKE ?", "%#{search}%")
end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/negocios_controller.rb
class NegociosController < ApplicationController
  before_action :set_negocio, only: [:show, :edit, :update, :destroy]

  # GET /negocios
  # GET /negocios.json

  def index
    @negocios = Negocio.all
    if params[:search]
      @negocios = Negocio.search(params[:search]).order("created_at DESC")
    else
      @negocios = Negocio.all.order('created_at DESC')
    end
  end
  
  # GET /negocios/1
  # GET /negocios/1.json
  def show
  end

  # GET /negocios/new
  def new
    @negocio = Negocio.new
  end

  # GET /negocios/1/edit
  def edit
  end

  # POST /negocios
  # POST /negocios.json
  def create
    @negocio = Negocio.new(negocio_params)

    respond_to do |format|
      if @negocio.save
        format.html { redirect_to @negocio, notice: 'Negocio was successfully created.' }
        format.json { render :show, status: :created, location: @negocio }
      else
        format.html { render :new }
        format.json { render json: @negocio.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /negocios/1
  # PATCH/PUT /negocios/1.json
  def update
    respond_to do |format|
      if @negocio.update(negocio_params)
        format.html { redirect_to @negocio, notice: 'Negocio was successfully updated.' }
        format.json { render :show, status: :ok, location: @negocio }
      else
        format.html { render :edit }
        format.json { render json: @negocio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /negocios/1
  # DELETE /negocios/1.json
  def destroy
    @negocio.destroy
    respond_to do |format|
      format.html { redirect_to negocios_url, notice: 'Negocio was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_negocio
      @negocio = Negocio.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def negocio_params
      params.require(:negocio).permit(:name, :desc, :body, :telephone, :cellphone, :address, :schedule, :email, :lat, :lng)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/negocios_helper.rb
module NegociosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Koala</title>
   <%= stylesheet_link_tag "mainstyle" %> 
   <%= javascript_include_tag "application" %>
<script src="//maps.google.com/maps/api/js?v=3.23&key=AIzaSyB3_3ykF6xL53DMi0byiQqRDaE6wkeZ7hY"></script>
<script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
<script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script>
</head>
<body>
<div id='jack-in-the-box'>
<header>
	<%= image_tag("logo.jpg", :alt => "koala logo") %>	
</header>

<%= yield %>
</div>
<footer>
	<div>
	  <nav id="primary_nav_wrap">
		<ul>
		  <li class="current-menu-item"><%= link_to 'Inicio', negocios_path %></li>
		  <li><%= link_to 'Registrate', new_negocio_path %></li>
		  <li><a href="#">Conocenos</a></li>
		  <li><a href="#">Terminos y Condiciones</a></li>
		  <li><a href="#">Contacto</a></li>
		</ul>
	  </nav>
	</div>
</footer>
</body>
</html>

app/views/negocios/_form.html.erb
<%= form_for(@negocio) do |f| %>
  <% if @negocio.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@negocio.errors.count, "error") %> prohibited this negocio from being saved:</h2>

      <ul>
      <% @negocio.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div id='add-form-wrap'>
<div id='add-form'>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :desc %><br>
    <%= f.text_area :desc %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :telephone %><br>
    <%= f.text_area :telephone %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_area :address %>
  </div>
  <div class="field">
    <%= f.label :cellphone %><br>
    <%= f.text_area :cellphone %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_area :email %>
  </div>
  <div class="field">
    <%= f.label :schedule %><br>
    <%= f.text_area :schedule %>
  </div>
  <div class="field">
    <%= f.label :lat %><br>
    <%= f.text_area :lat %>
  </div>  
  <div class="field">
    <%= f.label :lng %><br>
    <%= f.text_area :lng %>
  </div>  
  <div class="actions">
    <%= f.submit %>
  </div>
  </div>
  </div>
</div>
<% end %>

app/views/negocios/edit.html.erb
<h1>Editing Negocio</h1>

<%= render 'form' %>

<%= link_to 'Show', @negocio %> |
<%= link_to 'Back', negocios_path %>

app/views/negocios/index.html.erb
<p id="notice"><%= notice %></p>
<div id='search-box-wrapper'>
  <div id='search-box'>
  <%= form_tag(negocios_path, :method => "get", id: "search-form") do %>
    <%= text_field_tag :search, params[:search], placeholder: "Que estas buscando..." %>
    <div id='button'>
     <%= submit_tag "Buscar" %>
    </div>
  <% end %>
  </div>
</div>
<div id='search-results'>
  <% @negocios.each do |negocio| %>
  <div id='results-box'>
    <div id='name'><%= link_to negocio.name, negocio %></div>
    <div id='desc'><%= negocio.desc %></div>
  </div>
  <% end %>
</div>

app/views/negocios/new.html.erb
<h1></h1>

<%= render 'form' %>

app/views/negocios/show.html.erb
<p id="notice"><%= notice %></p>
<script type="text/javascript">
var lat = <%= @negocio.lat %>
var lng = <%= @negocio.lng %>

handler = Gmaps.build('Google');
handler.buildMap(
  {
    provider: {
      disableDefaultUI: true
      // here you can pass other Google Maps API options here
    },
    internal: {
      id: 'map'
    }
  },
  function() {
    markers = handler.addMarkers([
      {
        "lat":lat,
        "lng":lng,
        "picture": {
          "url": "https://cdn1.iconfinder.com/data/icons/Map-Markers-Icons-Demo-PNG/128/Map-Marker-Marker-Outside-Azure.png",
          "width":  36,
          "height": 36
        },
        "infowindow": 'hello!'
      }
    ]);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
  }
);		
</script>

<div id='back-btn'><%= link_to 'Back', negocios_path %></div>
<div id='header-wrap-promo'>
	<div id='header-promo'>
		<h1><%= @negocio.name %></h1>
	</div>
</div>
<div id='sub-wrap-promo'>
	<div id='sub-promo'>
		<%= @negocio.desc %>
	</div>
</div>
 <div id='body-wrap-promo'>
 	<div id='body-promo'>
 		<%= @negocio.body %>
 	</div>
 </div>

  <div id='contact-wrap-promo'>
  	<div id='contact-promo'>
  		<div id='contact-header'>Contacto</div>
  		<div id='address'>Direccion: <%= @negocio.address %></div>
  		<div id='cellphone'>Celular: <%= @negocio.cellphone %></div>
  		<div id='telephone'>Telefono: <%= @negocio.telephone %></div>
  		<div id='schedule'>Horario: <%= @negocio.schedule %></div>
  		<div style='width: 800px;'>
  			<div id="map" style='width: 800px; height: 400px;'></div>
		</div>
  	</div>
  </div>
<div>
</div>

<!--<%= link_to 'Edit', edit_negocio_path(@negocio) %> -->